### ISSUE TITLE
Add Font awesome icons to the markers.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#148]
**Have an idea for an additional feature?**
(a) Describe the feature

We would like to use the Font Awesome icons inside the marker pins.

(b) How does it need to perform?

As above, it should show the markers with the Fontawesome icons inside, they should be the same icons we currently use when displaying the business details.

(c) How will we code it?

When I last looked I found there was already an extension written for LeafetJS that will do this for us.

**Comment by dsummersl** [comment]
Sorry for the slow delay, I'm starting on this tonight!

**Comment by readingdancer** [comment]
No worries, great to have you back again :)

Did you find the package for adding the icons?

**Comment by dsummersl** [comment]
There are two out there that come up - one very old, one somewhat old. I went with the newer (`leaflet-fa-markers`). I think I'm going to back to the leaflet site to give the list of plugins a good long look b/c I'm not happy with the lack of styling options I've got...at any rate I've refactored the `businessIcon` function used on the business details component into a central place so that it can be reused on the map.

Here's a screen shot thus far (pretty sure I'm going to try a different library though, so I expect this will improve!)

![image](https://user-images.githubusercontent.com/30856/79982010-9b4f6a80-8473-11ea-9918-1c4adc6b8df8.png)

**Comment by readingdancer** [comment]
Hi @dsummersl 

That's a great start, are you able to use the original markers in our project? If so, I have created new versions without the dots in the middle using our color scheme which should work well with the icons.

The only other comment I'd have, is the shadow seems to have disappeared, I would guess it'll be pretty easy to add that back in if you take a look at the original bit of code :)

Thanks again,

Chris

![SolidBlue1](https://user-images.githubusercontent.com/4398217/79993072-58e15a00-8482-11ea-9dcf-bf5b5a875454.png)
![SolidBlue2x](https://user-images.githubusercontent.com/4398217/79993075-5979f080-8482-11ea-99bd-051ec4553589.png)
![SolidGrey2](https://user-images.githubusercontent.com/4398217/79993076-5979f080-8482-11ea-941d-ae4251e14465.png)
![SolidGrey2x](https://user-images.githubusercontent.com/4398217/79993077-5979f080-8482-11ea-830a-7df81885835c.png)
![SolidRed2x](https://user-images.githubusercontent.com/4398217/79993078-5a128700-8482-11ea-8941-249227ccaee3.png)
![SolidRed3](https://user-images.githubusercontent.com/4398217/79993081-5a128700-8482-11ea-96da-fbd37ad0582c.png)

I look forward to seeing your PR 👍

**Comment by dsummersl** [comment]
I couldn't use the original markers or the shadow with the first library tried :') which is part of why I'm back on the hunt for other options (it also didn't support sizing the fontawesome icons within the pin, which I wanted to do...)...keep you posted, and thanks for the pins!

**Comment by readingdancer** [comment]
This has now been put live, thanks again @dsummersl  :)
