### ISSUE TITLE
Enable a list view for resources

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#242]
Create a list-only view for non-location-based resources, similar to the example shown below from the  Bay Area site (see collapsed view and expanded view)

See the site: https://www.bayareacommunity.org/
Find the code: https://github.com/dcl-covid-19/mega-map-dev

![Screen Shot 2020-06-25 at 7 34 14 PM](https://user-images.githubusercontent.com/58799043/85805688-025ef900-b71b-11ea-903c-d68e46b8e216.png)

![Screen Shot 2020-06-25 at 7 34 03 PM](https://user-images.githubusercontent.com/58799043/85805694-0559e980-b71b-11ea-92ad-81f50d50f99c.png)

**Comment by glitchedmob** [comment]
After talking with @readingdancer I believe we have a good way to tackle this. 

- For desktop everything stays just about the same with the exception of the sidebar getting a little wider.
- On mobile we're going to move the "What do you need?" dropdown to be fixed just below the current navigation. Eventually this will be replaced with a search box.
- Also on mobile the listing of items will come from the bottom instead of the side. This listing will be a full screen takeover with an option to return back to the map view. Also on the map view there will be an option to return to the list view.

**Comment by glitchedmob** [comment]
<img width="442" alt="Screen Shot 2020-06-28 at 11 15 02 PM" src="https://user-images.githubusercontent.com/9029666/85972334-537a2180-b995-11ea-8e91-313396533569.png">
<img width="441" alt="Screen Shot 2020-06-28 at 11 15 28 PM" src="https://user-images.githubusercontent.com/9029666/85972340-56751200-b995-11ea-9663-680be425b1c2.png">


Some examples from the mobile version of Google Maps

**Comment by readingdancer** [comment]
@all-contributors add @glitchedmob as code, ideas, design
