### ISSUE TITLE
Increase visibility of the arrow that shrinks/expands the side tab

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#89]
**Need work on an existing feature? **

Currently, there is a small, light grey arrow that is used to shrink or expand the side bar. This arrow can be difficult to notice, particularly on a mobile platform when trying to expand the side bar.

Can we change the size or color of the arrow to make it obvious to users?

![Screen Shot 2020-04-04 at 3 19 43 PM](https://user-images.githubusercontent.com/58799043/78459584-09c8b600-7688-11ea-9383-c63b611bca45.png)

![Screen Shot 2020-04-04 at 3 19 36 PM](https://user-images.githubusercontent.com/58799043/78459585-0a614c80-7688-11ea-9463-7b2e58efc860.png)

**Comment by readingdancer** [comment]
I modeled this on the Google Map side bar which I thought a lot of people would be used to using:

![Google Map Side Tab Example](https://user-images.githubusercontent.com/4398217/79285421-867b4180-7e8b-11ea-9c71-d98497afa00a.jpg)

Theirs is a few pixels wider, so we could certainly make ours wider, I also like their hover effect which happens when you hover over it both to open and close, to close it say " Collapse side panel "

If someone else works on this, please make sure that if you implement the hover effect that the text strings are added to the English translation file and then let me know so I can generate the rest of the translations :)

@KM-Hanson - Do you think the above will be ok or do you want to make it stand out even more?

**Comment by KM-Hanson** [comment]
@readingdancer 

Yes - this feature is modeled on Google maps. Note, though.....

(1) I don't think many people actually shrink the sidebar when using Google maps on a desktop ( I never noticed it before working on our site!)

(2) The sidebar is not used on the mobile version of Google maps. The mobile version of Google maps looks entirely different. I've had people comment on the difficulty of finding the shrink/expand arrow on our mobile version, so anything we can do to make it more visible will help.

The hover effect is nice.... but do people "hover" much on mobile?

Could we combine a change in arrow color with a hover feature?

**Comment by readingdancer** [comment]
Hi @KM-Hanson 

I have tried to do as you suggested, I have made the tab 50% wider, increase the shadow behind it and changed the color of the arrow to match the button color. ( which is one of our "brand" colors )

I have also added a hover effect ( which is translated into all languages ) this will only work on a desktop as hover effects do not work on mobile.

![Open Search Panel](https://user-images.githubusercontent.com/4398217/79661712-6052eb80-8182-11ea-928f-9d880d24990d.png)

Beyond this, we will need to completely refactor it and raise a new ticket, I do understand how Google Maps is different, but I think with the dialog open when you first visit our site, it is pretty intuitive as other apps like Slack work in the same way on mobile with their side menu sliding in and out from the left.

**Comment by readingdancer** [comment]
Ok, so for now I have removed the tooltips as they seem to break on mobile, as they are not part of making the tab more visible on mobile, I will close this ticket and we can have a new ticket for adding the tool tips in the future ( if I don't figure it out tomorrow )
